Added user manual for Xero, Quickbooks and Zohobooks modules
akaunting/docs pull request #38
Opened 2021-10-12 09:46 UTC by stojankukrika

Added user manual for Xero, Quickbooks and Zohobooks modules

2021-10-12 13:01 UTC, halimturkoglu requested changes

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/quickbooks.md
> +Need a custom functionality in [Akaunting](https://akaunting.com), or want to develop a new feature, feel free to email us on stojan.kukrika@gmail.com.
We can't accept this line as it's not related to the app.

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/xero.md
> +Need a custom functionality in [Akaunting](https://akaunting.com), or want to develop a new feature, feel free to email us on stojan.kukrika@gmail.com.
We can't accept this line as it's not related to the app.

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/zohobooks.md
> +Need a custom functionality in [Akaunting](https://akaunting.com), or want to develop a new feature, feel free to email us on stojan.kukrika@gmail.com.
We can't accept this line as it's not related to the app.

2021-10-12 13:01 UTC, halimturkoglu commented on en/MENU.md
> +		* [Quickbooks](app-manual/import-export/quickbooks)
It should be `QuickBooks`.

2021-10-12 13:01 UTC, halimturkoglu commented on en/MENU.md
> +		* [Zohobooks](app-manual/import-export/zohobooks)
It should be `Zoho Books`.

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/quickbooks.md
> +**Step3:** Connect to your Qucikbooks account.
It should be `QuickBooks`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/quickbooks.md
> +**Step1:** Find [Here](https://akaunting.com/apps/quickbooks) "**Quickbooks**" on Akaunting app store and click _Install_.
It should be `QuickBooks`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/quickbooks.md
> +**Step2:** Click Settings then "Quickbooks" in the right menu.
It should be `QuickBooks`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/quickbooks.md
> +**Step4:** After connect to your Quickbooks account you can select from menu items which data you like to copy from your Quickbooks into Akaunting app.
It should be QuickBooks

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/quickbooks.md
> +**Step1:** Find [Here](https://akaunting.com/apps/quickbooks) "**Quickbooks**" on Akaunting app store and click _Install_.
It should be `Akaunting App Store`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/xero.md
> +**Step1:** Find [Here](https://akaunting.com/apps/xero) "**Xero**" on Akaunting app store and click _Install_.
It should be `Akaunting App Store`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/zohobooks.md
> +**What's Zohobooks?**
It should be `ZohoBooks`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/zohobooks.md
> +**Step1:** Find [Here](https://akaunting.com/apps/zohobooks) "**Zohobooks**" on Akaunting app store and click _Install_.
It should be `ZohoBooks` and `Akaunting App Store`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/zohobooks.md
> +**Step2:** Click Settings then "Zohobooks" in the right menu.
It should be `ZohoBooks`

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/zohobooks.md
> +**Step3:** Connect to your Zohobooks account.
It should be ZohoBooks

2021-10-12 13:01 UTC, halimturkoglu commented on en/app-manual/import-export/zohobooks.md
> +**Step4:** After connect to your Zohobooks account you can select from menu items which data you like to copy from your Zohobooks into Akaunting app.
It should be `ZohoBooks`

2021-11-15 07:25 UTC, halimturkoglu requested changes
There are a few more changes that need to be done.

2021-11-15 07:58 UTC, stojankukrika commented
@halimturkoglu can you tell me what they are?

2021-11-30 14:30 UTC, merged